"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { fetchPhoenixFeed, type Tournament, type TournamentFeed as Feed } from "@/lib/splinterlands";

type Standing = { name: string; points: number; played: number; wins: number; podiums: number; form: string[] };

const seriesCopy = { short: "Monday Night Madness", season: "Afterdark Ascent", qualifier: "Top 8 qualify", unit: "pts" };

function mondayPoints(finish: number) { if (finish === 1) return 12; if (finish === 2) return 9; if (finish <= 4) return 7; if (finish <= 8) return 4; if (finish <= 16) return 2; return finish > 0 ? 1 : 0; }
function buildStandings(tournaments: Tournament[]): Standing[] {
  const playerMap = new Map<string, Standing>();
  for (const tournament of tournaments.filter((item) => item.status === 2)) for (const result of tournament.players) {
    const current = playerMap.get(result.name) ?? { name: result.name, points: 0, played: 0, wins: 0, podiums: 0, form: [] };
    current.points += mondayPoints(result.finish); current.played += 1; current.wins += result.finish === 1 ? 1 : 0; current.podiums += result.finish > 0 && result.finish <= 4 ? 1 : 0; current.form.push(result.finish > 0 ? String(result.finish) : "—"); playerMap.set(result.name, current);
  }
  return [...playerMap.values()].sort((a, b) => b.points - a.points || b.wins - a.wins || b.podiums - a.podiums || a.name.localeCompare(b.name));
}
function formatDate(value: string, withTime = false) { return new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", ...(withTime ? { hour: "2-digit", minute: "2-digit", timeZone: "UTC", timeZoneName: "short" } : {}) }).format(new Date(value)); }

export default function Home() {
  const [query, setQuery] = useState(""); const [expanded, setExpanded] = useState<string | null>(null);
  const [feed, setFeed] = useState<Feed>({ organiser: "phoenixevents", tournaments: [], syncedAt: null }); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false);
  const loadFeed = useCallback(async (manual = false) => { if (manual) setRefreshing(true); try { const onGitHubPages = window.location.hostname.endsWith("github.io"); let data: Feed; if (onGitHubPages) data = await fetchPhoenixFeed(); else { const response = await fetch("/api/tournaments", { cache: "no-store" }); data = (await response.json()) as Feed; if (!response.ok) throw new Error(data.error ?? "Sync failed"); } setFeed(data); } catch (error) { setFeed((current) => ({ ...current, error: error instanceof Error ? error.message : "Sync failed" })); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { loadFeed(); const timer = window.setInterval(() => loadFeed(), 300_000); return () => window.clearInterval(timer); }, [loadFeed]);
  const copy = seriesCopy; const seriesEvents = feed.tournaments; const completedEvents = seriesEvents.filter((event) => event.status === 2);
  const nextEvent = [...seriesEvents].filter((event) => event.status !== 2).sort((a, b) => new Date(a.startDate).getTime() - new Date(b.startDate).getTime())[0]; const standings = useMemo(() => buildStandings(feed.tournaments), [feed.tournaments]); const rows = standings.filter((row) => row.name.toLowerCase().includes(query.toLowerCase()));

  return <main>
    <header className="site-header"><a className="brand" href="#top" aria-label="Phoenix Reborn standings home"><img src="./phoenix-reborn-logo.png" alt="" /><span><b>Phoenix Reborn</b><small>Series HQ</small></span></a><nav aria-label="Primary navigation"><a href="#standings">Standings</a><a href="#results">Results</a><a href="#format">Format</a></nav><a className="watch" href="https://www.twitch.tv/phoenixreborntv" target="_blank" rel="noreferrer">Watch live <span>↗</span></a></header>
    <section className="hero" id="top"><div className="hero-glow" /><div className="hero-copy"><p className="eyebrow"><span className="live-dot" /> Live from the Splinterlands API</p><h1>Every battle.<br/><em>Every point.</em></h1><p className="intro">Follow the climb across the Phoenix Reborn tournament series. Official tables, event results and the battles that decided them.</p><div className="series-switch"><span className="active"><span>MNM</span> Monday Night Madness</span></div></div>
      <aside className="next-card"><p>{nextEvent ? "Next in the arena" : "Tournament feed"}</p>{nextEvent ? <><strong>{formatDate(nextEvent.startDate)}</strong><h2>{nextEvent.name}</h2><div><span>{formatDate(nextEvent.startDate, true).split(", ").at(-1)}</span><span>{nextEvent.format.replaceAll("_", " ")}</span></div><a href="https://splinterlands.com/tournaments" target="_blank" rel="noreferrer">View tournament <span>↗</span></a></> : <div className="awaiting"><strong>Awaiting<br/>first event</strong><p>No tournaments created by <b>@phoenixevents</b> are visible yet. This page will populate automatically.</p><a href="https://splinterlands.com/tournaments" target="_blank" rel="noreferrer">Open tournaments <span>↗</span></a></div>}</aside></section>
    <section className="ticker" aria-label="Season summary"><div><small>Selected series</small><b>{copy.short}</b></div><div><small>Season</small><b>{copy.season}</b></div><div><small>API events found</small><b>{seriesEvents.length}</b></div><div><small>Qualification</small><b>{copy.qualifier}</b></div></section>
    <section className="sync-strip" aria-live="polite"><span className={feed.error ? "sync-error" : ""}>{feed.error ? "Feed temporarily unavailable" : loading ? "Connecting to Splinterlands…" : `Synced with @${feed.organiser}${feed.syncedAt ? ` · ${new Date(feed.syncedAt).toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" })}` : ""}`}</span><button onClick={() => loadFeed(true)} disabled={refreshing}>{refreshing ? "Refreshing…" : "Refresh now"}</button></section>
    <section className="content-section standings-section" id="standings"><div className="section-heading"><div><p className="eyebrow">The climb</p><h2>Current standings</h2><p className="demo-note">Official results · updated automatically every five minutes</p></div><label className="search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Find a player" aria-label="Find a player" /></label></div><div className="leaderboard-shell"><div className="table-head"><span>Rank</span><span>Player</span><span>Events</span><span>Wins</span><span>Recent form</span><span>Points</span></div>{rows.map((row) => { const rank = standings.findIndex((item) => item.name === row.name) + 1; return <div className={`table-row ${rank <= 8 ? "qualified" : ""}`} key={row.name}><span className="rank">{String(rank).padStart(2, "0")}</span><span className="player"><i>{row.name.slice(0, 2).toUpperCase()}</i><b>{row.name}</b>{rank <= 3 && <small>{rank === 1 ? "Leader" : "Podium"}</small>}</span><span>{row.played}</span><span>{row.wins}</span><span className="form">{row.form.slice(0, 3).map((finish, index) => <i key={index}>{finish}</i>)}</span><span className="points">{Number.isInteger(row.points) ? row.points : row.points.toFixed(1)}<small>{copy.unit}</small></span></div>; })}{!loading && rows.length === 0 && <div className="empty-state"><span>00</span><h3>{query ? `No player matches “${query}”` : "The table is ready"}</h3><p>{query ? "Try a different IGN." : `Standings will appear here as soon as @${feed.organiser} completes the first ${copy.short} event.`}</p></div>}<div className="table-key"><span><i className="key-line" /> Finale qualification zone</span><span>{completedEvents.length ? `${completedEvents.length} completed event${completedEvents.length === 1 ? "" : "s"}` : "Pre-season"}</span></div></div></section>
    <section className="content-section results-section" id="results"><div className="section-heading"><div><p className="eyebrow">Battle log</p><h2>Event results</h2></div><a href="https://splinterlands.com/tournaments" target="_blank" rel="noreferrer">Splinterlands tournaments ↗</a></div><div className="event-list">{completedEvents.map((event, index) => { const sortedPlayers = [...event.players].sort((a, b) => a.finish - b.finish); const winner = sortedPlayers.find((player) => player.finish === 1); const runner = sortedPlayers.find((player) => player.finish === 2); return <article className={expanded === event.id ? "event-card open" : "event-card"} key={event.id}><button className="event-summary" onClick={() => setExpanded(expanded === event.id ? null : event.id)} aria-expanded={expanded === event.id}><span className="event-no">{String(completedEvents.length - index).padStart(2, "0")}</span><span className="event-name"><small>{formatDate(event.startDate)} · Final</small><b>{event.name}</b></span><span className="event-winner"><small>Winner</small><b>{winner?.name ?? "Result pending"}</b></span><span className="field"><small>Field</small><b>{event.entrants}</b></span><span className="chevron">⌄</span></button>{expanded === event.id && <div className="event-detail"><div className="podium"><span><small>Champion</small><b>01 · {winner?.name ?? "—"}</b></span><span><small>Runner-up</small><b>02 · {runner?.name ?? "—"}</b></span></div><div className="battle-links">{event.battles.length ? event.battles.map((battle) => <a key={battle.id} href={`https://splinterlands.com/?p=battle&id=${battle.id}`} target="_blank" rel="noreferrer"><span>▶</span>{battle.label}<small>{battle.players} ↗</small></a>) : <p className="no-battles">Replay links are not yet available from the API for this event.</p>}</div></div>}</article>; })}{!loading && completedEvents.length === 0 && <div className="empty-state results-empty"><span>API</span><h3>No completed events yet</h3><p>Results and direct battle replays will be added here automatically after the first tournament created by <b>@phoenixevents</b>.</p></div>}</div></section>
    <section className="format-section" id="format"><div><p className="eyebrow">Your journey</p><h2>Play.<br/>Climb.<br/>Stand tall.</h2></div><div className="format-grid"><article><span>01</span><h3>Play in weekly events</h3><p>Enter Monday Night Madness each week and battle for your place in the field.</p></article><article><span>02</span><h3>Accumulate points</h3><p>Every valid finish adds points to your season total and moves you up the table.</p></article><article><span>03</span><h3>Stand tall on the leaderboard</h3><p>Track your rise, hold a top-eight position and earn your place in the finale.</p></article></div></section>
    <footer><div className="brand"><img src="./phoenix-reborn-logo.png" alt="" /><span><b>Phoenix Reborn</b><small>Rise again. Queue again.</small></span></div><p>Community-run Splinterlands competition.<br/>Official organiser: @phoenixevents</p><div><a href="#standings">Standings</a><a href="#results">Results</a><a href="https://splinterlands.com/tournaments">Enter tournaments ↗</a></div></footer>
  </main>;
}
